/// Marked date table: one row per calendar day from 2010-01-01 to 2014-12-31, with calendar and fiscal (July-start) attributes.
table 'Dim Date'
	lineageTag: ef389f36-7393-496f-a76e-bd0e59602a1b
	dataCategory: Time

	/// The calendar date. Marked as the table's key column for time intelligence.
	column Date
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: dd197f9a-f7a7-44a9-bd35-6090325a67d7
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Calendar year, e.g. 2013.
	column Year
		dataType: int64
		formatString: #,##0
		lineageTag: d7088b27-ab05-4ed4-ad8b-7c01aa54966a
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	/// Calendar quarter number (1-4), used to sort the Quarter column.
	column 'Quarter No'
		dataType: int64
		formatString: #,##0
		lineageTag: 57109d7b-e511-49cd-9de4-7233145e71d4
		summarizeBy: none
		sourceColumn: Quarter No

		annotation SummarizationSetBy = Automatic

	/// Calendar quarter label, e.g. "Q3". Sorted by Quarter No.
	column Quarter
		dataType: string
		lineageTag: 835cc572-f732-44a3-ac4c-e5901a765619
		summarizeBy: none
		sourceColumn: Quarter
		sortByColumn: 'Quarter No'

		annotation SummarizationSetBy = Automatic

	/// Calendar month number (1-12), used to sort Month Name.
	column 'Month No'
		dataType: int64
		formatString: #,##0
		lineageTag: b45d780b-2447-4100-bb09-07ef89af9a58
		summarizeBy: none
		sourceColumn: Month No

		annotation SummarizationSetBy = Automatic

	/// Abbreviated month name, e.g. "Jan". Sorted by Month No.
	column 'Month Name'
		dataType: string
		lineageTag: 8d6b83ee-cb15-4281-bc62-6ce5cf8c4e49
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: 'Month No'

		annotation SummarizationSetBy = Automatic

	/// Year and month label, e.g. "2013-07". Sorted by Year Month Key.
	column Year-Month
		dataType: string
		lineageTag: c1e63962-df6d-4771-ba63-81113ba5130e
		summarizeBy: none
		sourceColumn: Year-Month
		sortByColumn: 'Year Month Key'

		annotation SummarizationSetBy = Automatic

	/// Numeric YYYYMM sort key behind Year-Month, e.g. 201307.
	column 'Year Month Key'
		dataType: int64
		formatString: #,##0
		lineageTag: 654a22fd-8db3-410c-b6d3-2e365a79b834
		summarizeBy: none
		sourceColumn: Year Month Key

		annotation SummarizationSetBy = Automatic

	/// ISO day-of-week number, Monday = 1 through Sunday = 7. Used to sort Day Name.
	column 'Day of Week No (Mon=1)'
		dataType: int64
		formatString: #,##0
		lineageTag: e8e23285-c4bd-4782-abef-ca5ca6c32404
		summarizeBy: none
		sourceColumn: Day of Week No (Mon=1)

		annotation SummarizationSetBy = Automatic

	/// Abbreviated weekday name, e.g. "Mon". Sorted by Day of Week No.
	column 'Day Name'
		dataType: string
		lineageTag: 6c0da15b-bdea-4225-811d-6715f74290c0
		summarizeBy: none
		sourceColumn: Day Name
		sortByColumn: 'Day of Week No (Mon=1)'

		annotation SummarizationSetBy = Automatic

	/// True for Saturday and Sunday.
	column 'Is Weekend'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: bf9cd805-1062-47b3-9aff-a9a1cfe979a5
		summarizeBy: none
		sourceColumn: Is Weekend

		annotation SummarizationSetBy = Automatic

	/// ISO-8601 week-of-year number (nearest-Thursday method).
	column 'Week of Year (ISO)'
		dataType: int64
		formatString: #,##0
		lineageTag: a9f66701-7e8e-4c14-af9b-659a9c6ce6ec
		summarizeBy: none
		sourceColumn: Week of Year (ISO)

		annotation SummarizationSetBy = Automatic

	/// Fiscal year number, named by its end year (fiscal year starts in the month given by the FiscalYearStartMonth parameter).
	column 'Fiscal Year No'
		dataType: int64
		formatString: #,##0
		lineageTag: fef952fa-e5d3-46a6-9a1f-ef061ba57477
		summarizeBy: none
		sourceColumn: Fiscal Year No

		annotation SummarizationSetBy = Automatic

	/// Fiscal year label, e.g. "FY2013".
	column 'Fiscal Year'
		dataType: string
		lineageTag: f3b18360-8a03-45bb-8d29-1dd1145d30ad
		summarizeBy: none
		sourceColumn: Fiscal Year

		annotation SummarizationSetBy = Automatic

	/// Fiscal month number, 1 = first month of the fiscal year.
	column 'Fiscal Month No'
		dataType: int64
		formatString: #,##0
		lineageTag: 2bc55b69-0651-421d-ad41-fd48be33afdc
		summarizeBy: none
		sourceColumn: Fiscal Month No

		annotation SummarizationSetBy = Automatic

	/// Fiscal quarter number (1-4) within the fiscal year.
	column 'Fiscal Quarter No'
		dataType: int64
		formatString: #,##0
		lineageTag: 49c32861-5ae2-476d-a092-46b2f671c60b
		summarizeBy: none
		sourceColumn: Fiscal Quarter No

		annotation SummarizationSetBy = Automatic

	/// Fiscal quarter label, e.g. "FQ1". Sorted by Fiscal Quarter No.
	column 'Fiscal Quarter'
		dataType: string
		lineageTag: 335bfa18-fd1d-4e79-8e68-46407a341dac
		summarizeBy: none
		sourceColumn: Fiscal Quarter
		sortByColumn: 'Fiscal Quarter No'

		annotation SummarizationSetBy = Automatic

	/// Fiscal year and month label, e.g. "FY2013-01". Sorted by Fiscal Year Month Key.
	column 'Fiscal Year-Month'
		dataType: string
		lineageTag: e03d471f-1c9a-464e-a0a7-dda3c766d18d
		summarizeBy: none
		sourceColumn: Fiscal Year-Month
		sortByColumn: 'Fiscal Year Month Key'

		annotation SummarizationSetBy = Automatic

	/// Numeric sort key behind Fiscal Year-Month. Hidden: pure sort helper, not a reporting attribute.
	column 'Fiscal Year Month Key'
		dataType: int64
		isHidden
		formatString: #,##0
		lineageTag: 34357b8e-19aa-488e-ae4d-cf929d69e5fa
		summarizeBy: none
		sourceColumn: Fiscal Year Month Key

		annotation SummarizationSetBy = Automatic

	/// Calendar drill path: Year -> Quarter -> Month Name -> Date.
	hierarchy Calendar
		lineageTag: 8352ead0-4caf-4ba8-bf86-0567ca4a1dc2

		level Year
			lineageTag: ef0d22f1-ed30-40ee-b7a4-d786caef328d
			column: Year

		level Quarter
			lineageTag: 9c88635d-4283-427b-9cf6-52e315eeb3bb
			column: Quarter

		level 'Month Name'
			lineageTag: 8238f84d-8b0c-4e7d-b141-21bec9725716
			column: 'Month Name'

		level Date
			lineageTag: 361568ba-c67f-4225-a685-1d6a99f7ed76
			column: Date

	/// Fiscal drill path: Fiscal Year -> Fiscal Quarter -> Fiscal Year-Month -> Date.
	hierarchy Fiscal
		lineageTag: 381c45a2-20c9-40b6-8f4d-b9efeea491ef

		level 'Fiscal Year'
			lineageTag: 0d1f4c08-79ae-4a6a-acad-2fef3823edae
			column: 'Fiscal Year'

		level 'Fiscal Quarter'
			lineageTag: 715a803d-0e9b-414b-9c90-cdc62010eeff
			column: 'Fiscal Quarter'

		level 'Fiscal Year-Month'
			lineageTag: 6b43416a-dc3c-412e-a6ab-f1ef68af53ca
			column: 'Fiscal Year-Month'

		level Date
			lineageTag: 1bc8779a-4ef8-482f-87e0-9baced73d4dc
			column: Date

	partition 'Dim Date' = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    // Range: 1 Jan 2010 (year of the earliest Order Date, 2010-12-29) through
				    // 31 Dec 2014 (year of the latest Due Date, 2014-02-09) — see
				    // docs/powerbi_reconciliation_results.md for the source dates.
				    StartDate = #date(2010, 1, 1),
				    EndDate = #date(2014, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    Dates = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Converted to Table" = Table.FromList(Dates, Splitter.SplitByNothing(), {"Date"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Converted to Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter No" = Table.AddColumn(#"Added Year", "Quarter No", each Date.QuarterOfYear([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Quarter No", "Quarter", each "Q" & Text.From([Quarter No]), type text),
				    #"Added Month No" = Table.AddColumn(#"Added Quarter", "Month No", each Date.Month([Date]), Int64.Type),
				    #"Added Month Name" = Table.AddColumn(#"Added Month No", "Month Name", each Date.ToText([Date], "MMM"), type text),
				    #"Added Year-Month" = Table.AddColumn(#"Added Month Name", "Year-Month", each Text.From([Year]) & "-" & Text.PadStart(Text.From([Month No]), 2, "0"), type text),
				    #"Added Year Month Key" = Table.AddColumn(#"Added Year-Month", "Year Month Key", each [Year] * 100 + [Month No], Int64.Type),
				    #"Added Day of Week No" = Table.AddColumn(#"Added Year Month Key", "Day of Week No (Mon=1)", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added Day Name" = Table.AddColumn(#"Added Day of Week No", "Day Name", each Date.ToText([Date], "ddd"), type text),
				    #"Added Is Weekend" = Table.AddColumn(#"Added Day Name", "Is Weekend", each (Date.DayOfWeek([Date], Day.Monday) + 1) >= 6, type logical),
				    #"Added Week of Year (ISO)" = Table.AddColumn(#"Added Is Weekend", "Week of Year (ISO)", each
				        let
				            DOW = Date.DayOfWeek([Date], Day.Monday) + 1,
				            ThursdayDate = Date.AddDays([Date], 4 - DOW),
				            ISOYearStart = #date(Date.Year(ThursdayDate), 1, 1)
				        in
				            Number.RoundUp((Duration.Days(ThursdayDate - ISOYearStart) + 1) / 7),
				        Int64.Type),
				    #"Added Fiscal Year No" = Table.AddColumn(#"Added Week of Year (ISO)", "Fiscal Year No", each if [Month No] >= FiscalYearStartMonth then [Year] + 1 else [Year], Int64.Type),
				    #"Added Fiscal Year" = Table.AddColumn(#"Added Fiscal Year No", "Fiscal Year", each "FY" & Text.From([Fiscal Year No]), type text),
				    #"Added Fiscal Month No" = Table.AddColumn(#"Added Fiscal Year", "Fiscal Month No", each Number.Mod([Month No] - FiscalYearStartMonth + 12, 12) + 1, Int64.Type),
				    #"Added Fiscal Quarter No" = Table.AddColumn(#"Added Fiscal Month No", "Fiscal Quarter No", each Number.RoundUp([Fiscal Month No] / 3), Int64.Type),
				    #"Added Fiscal Quarter" = Table.AddColumn(#"Added Fiscal Quarter No", "Fiscal Quarter", each "FQ" & Text.From([Fiscal Quarter No]), type text),
				    #"Added Fiscal Year-Month" = Table.AddColumn(#"Added Fiscal Quarter", "Fiscal Year-Month", each [Fiscal Year] & "-" & Text.PadStart(Text.From([Fiscal Month No]), 2, "0"), type text),
				    #"Added Fiscal Year Month Key" = Table.AddColumn(#"Added Fiscal Year-Month", "Fiscal Year Month Key", each [Fiscal Year No] * 100 + [Fiscal Month No], Int64.Type)
				in
				    #"Added Fiscal Year Month Key"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

