table 'Dim Product'
	lineageTag: c6dacd88-19c9-491f-a17a-66f7e3393b32

	column 'Product Key'
		dataType: int64
		formatString: 0
		lineageTag: 4076625b-d1c7-4686-a4ac-0b63096a0d1e
		summarizeBy: none
		sourceColumn: Product Key

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: int64
		formatString: 0
		lineageTag: 317e0318-594d-4710-bade-bb92e68b484e
		summarizeBy: count
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column 'Product Number'
		dataType: string
		lineageTag: 86135714-c5ee-4be5-98b6-e20a92e6570a
		summarizeBy: none
		sourceColumn: Product Number

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 38813286-ea98-4e15-aa08-640387bee912
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column 'Category ID'
		dataType: string
		lineageTag: 2c919ce8-e101-4289-9ff9-ec7dab1c0c1f
		summarizeBy: none
		sourceColumn: Category ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 0bf78145-da91-4fdc-880e-fd799a4986ed
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Subcategory
		dataType: string
		lineageTag: 905acf11-c635-45c3-8f59-33122b3a224d
		summarizeBy: none
		sourceColumn: Subcategory

		annotation SummarizationSetBy = Automatic

	column Maintenance
		dataType: string
		lineageTag: 59e34e5d-0f77-43ed-b6d1-ab0472e5e167
		summarizeBy: none
		sourceColumn: Maintenance

		annotation SummarizationSetBy = Automatic

	column Cost
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 9e188f30-24d1-4dca-9f59-584ffde64115
		summarizeBy: sum
		sourceColumn: Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Product Line'
		dataType: string
		lineageTag: b6cde4a3-8930-44f9-ba6f-d600e78fcd84
		summarizeBy: none
		sourceColumn: Product Line

		annotation SummarizationSetBy = Automatic

	column 'Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f78b3bf0-1b04-4974-add3-d35d420c9caa
		summarizeBy: none
		sourceColumn: Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'Dim Product' = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = Sql.Database(ServerName, DatabaseName),
				    gold_dim_products = Source{[Schema="gold",Item="dim_products"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(gold_dim_products, {
				        {"product_key", "Product Key"},
				        {"product_id", "Product ID"},
				        {"product_number", "Product Number"},
				        {"product_name", "Product Name"},
				        {"category_id", "Category ID"},
				        {"category", "Category"},
				        {"subcategory", "Subcategory"},
				        {"maintenance", "Maintenance"},
				        {"cost", "Cost"},
				        {"product_line", "Product Line"},
				        {"start_date", "Start Date"}
				    }),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {
				        {"Product Key", Int64.Type},
				        {"Product ID", Int64.Type},
				        {"Product Number", type text},
				        {"Product Name", type text},
				        {"Category ID", type text},
				        {"Category", type text},
				        {"Subcategory", type text},
				        {"Maintenance", type text},
				        {"Cost", Currency.Type},
				        {"Product Line", type text},
				        {"Start Date", type date}
				    })
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

